
services:


  springboot-microservice-catalog:
    build: .

    ports:
      - "8080:8081"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_NAME: catalogue_db
      DB_USER: root
      DB_PASSWORD: root
    networks:
      - book_network

networks:
  book_network:
    driver: bridge
