services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catalogue_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3307:3306"
    networks:
      - book_network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h mysql -u ${MYSQL_USER} --password=${MYSQL_PASSWORD} || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10

  springboot-microservice-catalog:
    build: .
    container_name: catalog-service
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8081"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: catalogue_db
      DB_USER: testuser
      DB_PASSWORD: testpassword
    networks:
      - book_network

networks:
  book_network:
    driver: bridge

volumes:
  mysql_data:
