name: Springboot-microservice Docker Build & Push

on:
  push:
    branches:
      - development

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: dockdockgo2001/springboot-microservice-catalog

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -ntp clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build  -t $IMAGE_NAME:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push $IMAGE_NAME:latest
