name: Springboot-microservice

on:

  pull_request:
    branches:
      - development
  push:
    paths:
      - Springboot-microservice/**
    branches:
      - development

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./Springboot-microservice
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 21
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -ntp clean package